//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by patn.rc
//
#define IDC_SET                         3
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             102
#define IDP_FAILED_TO_CREATE            103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDI_STOP                        125
#define IDD_DATA_TRANSFORM              125
#define IDD_LOG_CONSTANT                127
#define IDR_MAINFRAME                   128
#define IDR_TABLETYPE                   129
#define IDR_FUSETYPE                    130
#define ARROW_RIGHT                     131
#define IDR_ASSOCTYPE                   132
#define IDD_EXPONENT                    133
#define IDR_HISTOGRAM                   134
#define IDD_NONZEROS_CONSTANT           135
#define IDD_PAGE_NEW_TABLE_OPTIONS      136
#define IDR_MENU_COLUMN                 137
#define IDB_SPLASH                      138
#define IDC_TOP_OF_COLUMN               139
#define IDD_ASSOCIATION_PAGE            140
#define IDC_DRAGGING_EW                 141
#define IDD_CLASSIFICATION_PAGE_ROWS    142
#define IDC_DRAGGING_NS                 143
#define IDD_ORDINATION_PAGE             144
#define IDC_CAN_DRAG_NS                 145
#define IDC_LEFT_OF_ROW                 146
#define IDC_SIZE_COLUMN                 147
#define IDC_SIZE_ROW                    148
#define IDC_CAN_DRAG_EW                 149
#define IDC_SIZE_HIDDEN_COLUMN          150
#define IDC_SIZE_HIDDEN_ROW             151
#define IDD_PICK_ASSOC_MATRIX           152
#define IDD_STARTUP                     153
#define IDI_BTN_OPEN                    154
#define IDD_ANALYSIS                    155
#define IDI_BTN_NEW                     156
#define IDD_CLASSIFICATION_PAGE_COLS    157
#define IDI_BTN_IMPORT                  158
#define IDD_ANALYSIS_RECIPE             159
#define IDB_STARTUP1                    160
#define IDD_PICK_FUSE_TABLE             161
#define IDD_SELECT_COLS_OR_ROWS         162
#define IDD_CLASSIFICATION_PAGE_ROWS1   163
#define IDD_ORDINATION_PAGE1            164
#define IDI_BTN_WIZARD                  165
#define IDD_FUSEFONT                    166
#define IDR_MENU_ROW                    167
#define IDD_PAGE_COLUMN_OPTIONS         168
#define IDD_PAGE_ROW_OPTIONS            169
#define IDD_TWAY_OPTIONS                170
#define IDR_TWAYTABLE                   171
#define IDR_GSTAVIEW                    172
#define IDR_3DVIEW                      173
#define IDR_3DVIEW_ICON                 173
#define IDR_SCAT                        174
#define IDR_ANOSIM                      175
#define IDR_3DXVIEW                     176
#define IDD_GSTA_OPTIONS                177
#define IDR_MENU_3DVIEW                 178
#define IDD_EDITTEXT                    179
#define IDD_COLOUR                      180
#define IDD_TABLEPROPERTIES             181
#define IDD_ODBC_CON_VALUES             182
#define IDR_MENU_DEND                   183
#define IDR_IMAGE                       184
#define IDR_TABLE                       185
#define IDR_MENU_TWAY                   188
#define IDR_TABLEANOSIM                 189
#define IDD_ATTRIBUTE                   190
#define IDR_BW                          191
#define IDD_PCCVECTORSELECTION          192
#define IDD_PATTERN_ORDER               193
#define IDD_KWOPTIONS                   194
#define IDD_NEWDIALOG                   195
#define IDD_EVALUATION                  196
#define IDD_EVALUATIONRECIPE            197
#define IDD_PCCMCAO_PAGE                198
#define IDD_KW_PAGE                     199
#define IDD_ANOSIM_PAGE                 200
#define IDD_ANOSIMRESULTS               201
#define IDD_KWRESULTS                   202
#define IDD_MCAORESULTS                 203
#define IDD_VIEWHISTORY                 204
#define IDD_INDIVIDUALGROUPS            205
#define IDD_CHOOSEANOSIM                206
#define IDD_PICK_ANOSIM                 207
#define IDD_SEL_SIZE                    208
#define IDD_SELECTOPTIONS               209
#define IDR_BOXWHISKER                  210
#define IDD_EDITTEXT2                   211
#define IDR_SCATTERPLOT                 212
#define IDR_SCATTPLOT                   213
#define IDC_3DROTATE                    226
#define IDR_HTML_3DLEGENDDIALOG         230
#define IDR_VIEWTOOLBAR                 231
#define IDD_GROUPS                      232
#define IDD_OBJECTSIZE                  233
#define IDD_APPENDOPTIONS               234
#define IDD_KWTHREASHOLD                235
#define IDB_APPEND02                    236
#define IDB_APPEND03                    237
#define IDB_APPEND04                    238
#define IDB_APPEND05                    239
#define IDB_APPEND06                    240
#define IDB_APPEND07                    241
#define IDB_APPEND08                    242
#define IDB_APPEND09                    243
#define IDR_PATTERN_FILE                243
#define IDB_APPEND10                    244
#define IDB_APPEND11                    245
#define IDB_APPEND12                    246
#define IDR_TEXT1                       246
#define IDB_APPEND13                    247
#define IDD_PROPERTIES_TABLEPROPERTIES  247
#define IDB_APPEND14                    248
#define IDD_PROPERTIES_VISIBLESTATISTICS 248
#define IDD_PROPERTIES_ORDINATIONDISPLAYTYPE 249
#define IDD_PROPERTIES_RANDOMTYPE       250
#define IDR_ABOUT_TEXT                  258
#define IDD_GETUSERIDENTITY             259
#define IDD_PROPERTIES_BWOBJECTS        260
#define IDD_PROPERTIES_FONT             261
#define IDD_FRAMECOUNT                  262
#define IDR_TABLETABS                   263
#define IDD_EXCEL_WORKSHEET             264
#define IDD_GETSERIALNUMBER             265
#define IDD_INSTALLHELP                 267
#define IDB_BITMAP1                     270
#define IDB_INSTALLHELP                 270
#define IDD_DIALOG1                     271
#define IDD_UPDATE_GUIDE                271
#define IDB_SPLASH1                     271
#define IDR_DEMO_MEDALS                 273
#define IDD_3DLEGEND                    275
#define IDD_CONSTANCY_FIDELITY          276
#define IDR_DLL1                        278
#define IDR_3DX9VIEW                    280
#define IDI_ICON1                       280
#define IDR_HISTOGRAM_ICON              281
#define IDR_SCATTERPLOT_ICON            282
#define IDR_STDTOOLBAR                  283
#define IDR_ASSOC_ICON                  283
#define IDD_DIALOG2                     284
#define IDR_DENDOGRAM_ICON              284
#define IDD_ASSIGNGROUPS                285
#define IDR_TWAY_ICON                   285
#define IDR_CONSTFID                    285
#define IDD_COL_COLOURS                 286
#define IDR_ANOSIM_ICON                 286
#define IDR_BW_ICON                     287
#define IDD_DIALOG3                     287
#define IDR_PCC_ICON                    288
#define IDR_MCAO_ICON                   289
#define IDC_RADIO_INIT_CELLS            1002
#define IDC_RADIO2                      1003
#define IDC_RADIO3                      1004
#define IDC_RADIO_STANDARD              1005
#define IDC_EDIT_NUM_ROWS               1006
#define IDC_EDIT_NUM_COLUMNS            1007
#define IDC_EDIT_COLUMN_WIDTH           1008
#define IDC_SET_PARMS_ROWS              1009
#define IDC_RANDOM_SEED                 1009
#define IDC_SPIN_DEC_PLACES             1010
#define IDC_SET_PARMS_COLUMNS           1011
#define IDC_RADIO_CUSTOM                1012
#define IDC_EDIT_MISSING_VALUE          1013
#define IDC_ROWS                        1014
#define IDC_ADD                         1015
#define IDC_ADD_ALL                     1016
#define IDC_REMOVE                      1017
#define IDC_REMOVE_ALL                  1020
#define IDC_EDIT_DECIMAL_PRECISION      1022
#define IDC_COLUMNS                     1023
#define IDC_OPTIONS                     1024
#define IDC_ALL                         1025
#define IDC_SELECTED                    1026
#define IDC_BTN_IMPORT                  1027
#define IDC_CONSTANT                    1028
#define IDC_GROUPS                      1029
#define IDC_BTN_OPEN                    1030
#define IDC_BTN_NEW                     1031
#define IDC_GROUP                       1032
#define IDC_BTN_WIZARD                  1033
#define IDC_LB_ALL                      1034
#define IDC_LB_SELECTED                 1035
#define IDC_EDIT_NEW                    1036
#define IDC_BTN_ADD                     1037
#define IDC_EDIT_OLD                    1038
#define IDC_BTN_ADD_ALL                 1039
#define IDC_LIST_NEW                    1040
#define IDC_LIST                        1040
#define IDC_BTN_REMOVE                  1041
#define IDC_LIST_OLD                    1042
#define IDC_BTN_REMOVE_ALL              1043
#define IDC_RADIO_COLUMNS               1044
#define IDC_MODIFY                      1045
#define IDC_DELETE                      1046
#define IDC_BTN_CLOSE                   1047
#define IDC_EXPONENT                    1048
#define IDC_UPDATE                      1049
#define IDC_RADIO_ROWS                  1050
#define IDC_RUN                         1051
#define IDC_CLOSE                       1052
#define IDC_CANCEL                      1053
#define IDC_EDIT_LABEL                  1054
#define IDC_CHECK_HIDE                  1055
#define IDC_RADIO_SIZETOFIT             1056
#define IDC_EDIT_GROUP                  1057
#define IDC_SCALE                       1058
#define IDC_COLSTD                      1059
#define IDC_ASCII_OUTPUT                1060
#define IDC_GLOBSTD                     1061
#define IDC_PRESABS                     1062
#define IDC_P                           1063
#define IDC_FILENAME                    1064
#define IDC_COLUMNS_YES                 1065
#define IDC_CHECK1                      1066
#define IDC_COLUMNS_NO                  1067
#define IDC_CHECK4                      1067
#define IDC_ASSOC_MEASURES              1068
#define IDC_NEW                         1069
#define IDC_GROUPNUM                    1070
#define IDC_NUM_GROUPS                  1071
#define IDC_CHECK2                      1072
#define IDC_FUSE                        1073
#define IDC_BUTTON1                     1074
#define IDC_SELECTNONE                  1074
#define IDC_ALOC                        1075
#define IDC_BUTTON4                     1075
#define IDC_EDIT1                       1076
#define IDC_FUSE_TECHNIQUE              1077
#define IDC_EDIT5                       1077
#define IDC_GROUPCOLOUR                 1078
#define IDC_EDIT2                       1079
#define IDC_BETA                        1080
#define IDC_EDIT6                       1080
#define IDC_COLOURBOX                   1081
#define IDC_BETA2                       1081
#define IDC_EDIT3                       1082
#define IDC_VISIBLEDEC_EDIT             1082
#define IDC_NONE                        1083
#define IDC_EDIT4                       1084
#define IDC_COLDEC                      1084
#define IDC_ALOC_ASSOC_MEASURE          1085
#define IDC_RED                         1086
#define IDC_ROWS_YES                    1087
#define IDC_GREEN                       1088
#define IDC_BUTTON2                     1089
#define IDC_COL_LABEL_FIELD             1090
#define IDC_BUTTON5                     1090
#define IDC_ROWS_NO                     1091
#define IDC_BLUE                        1092
#define IDC_ROW_LABEL_FIELD             1093
#define IDC_ANALYSIS_LAYOUT             1094
#define IDC_DATA_FIELD                  1095
#define IDC_DEND                        1096
#define IDC_BW                          1097
#define IDC_DSN                         1098
#define IDC_TABLE                       1099
#define IDC_TABLE_NAME                  1100
#define IDC_BW2                         1101
#define IDC_HIST                        1102
#define IDC_ALLCOLS                     1103
#define IDC_MATRIX                      1104
#define IDC_SELECTEDCOLS                1105
#define IDC_PROGRESS1                   1106
#define IDC_LABEL                       1107
#define IDC_TIMER                       1108
#define IDC_EDIT_RED                    1109
#define IDC_EDIT_GREEN                  1110
#define IDC_EDIT_BLUE                   1111
#define IDC_OK                          1112
#define IDC_RADIO4                      1113
#define IDC_2D                          1114
#define IDC_3D                          1115
#define IDC_ITERATIONS                  1116
#define IDC_LABELS                      1117
#define IDC_3D2                         1117
#define IDC_1D                          1117
#define IDC_COLUMN_ITERATIONS           1118
#define IDC_ITERATIONS2                 1119
#define IDC_SEED                        1120
#define IDC_PATTERNS                    1121
#define IDC_COLUMN_SEED                 1122
#define IDC_SEED2                       1123
#define IDC_OBJECTS                     1124
#define IDC_NUMVISIBLE                  1125
#define IDC_RESET                       1126
#define IDC_NUMVISIBLESPIN              1127
#define IDC_ASSIGN                      1128
#define IDC_CUTOFF                      1129
#define IDC_BUTTON3                     1130
#define IDC_NUMPERMUTATIONS             1131
#define IDC_THRESHOLD                   1132
#define IDC_PERCENT                     1133
#define IDC_PROGRESS                    1134
#define IDC_RESULTS1                    1135
#define IDC_RESULTS2                    1136
#define IDC_CALCULATE                   1137
#define IDC_RANDOM                      1138
#define IDC_EXISTLABEL                  1139
#define IDC_SAVERECIPE                  1140
#define IDC_WIDTH                       1141
#define IDC_HEIGHT                      1142
#define IDC_PHEIGHT                     1143
#define IDC_RADIO1                      1144
#define IDC_PWIDTH                      1145
#define IDC_SETPARMS                    1146
#define IDC_MCAO_ITERATIONS             1147
#define IDC_SCROLL_PATTERNS             1148
#define IDC_MCAO_SEED                   1149
#define IDC_SCROLL_OBJECTS              1150
#define IDC_ROW_ITERATIONS              1151
#define IDC_ROW_SEED                    1152
#define IDC_KW                          1153
#define IDC_PCC                         1154
#define IDC_MCAO                        1155
#define IDC_BEST                        1156
#define IDC_STAT                        1157
#define IDC_BEST2                       1158
#define IDC_STAT2                       1159
#define IDC_HISTORY                     1160
#define IDC_SETROWGROUPS                1161
#define IDC_ROWALLGROUPS                1162
#define IDC_ROWPAIRGROUPS               1163
#define IDC_SETCOLGROUPS                1164
#define IDC_TITLE                       1165
#define IDC_COLALLGROUPS                1166
#define IDC_ROWPAIRS                    1167
#define IDC_COLPAIRGROUPS               1168
#define IDC_COLPAIRS                    1169
#define IDC_1                           1170
#define IDC_OBJECTSIZE                  1170
#define IDC_2                           1171
#define IDC_EVALUATION1                 1171
#define IDC_3                           1172
#define IDC_EVALUATION2                 1172
#define IDC_4                           1173
#define IDC_EVALUATION3                 1173
#define IDC_5                           1174
#define IDC_APPENDLHS                   1174
#define IDC_6                           1175
#define IDC_APPENDBTM                   1175
#define IDC_ROW                         1176
#define IDC_APPENDBTMPLUS               1176
#define IDC_7                           1176
#define IDC_ORDERVALUE                  1177
#define IDC_APPENDLHSPLUS               1177
#define IDC_8                           1177
#define IDC_ORDERTABLE                  1178
#define IDC_COLUMNLABELS                1178
#define IDC_9                           1178
#define IDC_COLS                        1179
#define IDC_ROWLABELS                   1179
#define IDC_SUM                         1180
#define IDC_INPUTFORMAT                 1180
#define IDC_MEAN                        1181
#define IDC_MAXIMUM                     1182
#define IDC_RADIO7                      1183
#define IDC_MATCH                       1183
#define IDC_RADIO8                      1184
#define IDC_LESS                        1185
#define IDC_GREATER                     1186
#define IDC_CL                          1186
#define IDC_VALUE                       1187
#define IDC_RL                          1187
#define IDC_EQUAL                       1188
#define IDC_ORDTYPE                     1188
#define IDC_EVALUATIONS                 1189
#define IDC_RADIO5                      1189
#define IDC_ROWMEAN                     1190
#define IDC_RADIO6                      1190
#define IDC_ROWMAX                      1191
#define IDC_LONGDATE                    1191
#define IDC_COLMEAN                     1192
#define IDC_VERSION                     1192
#define IDC_ROWSUM                      1193
#define IDC_DISTRIBUTION                1193
#define IDC_ROWMIN                      1194
#define IDC_UNIFORMRANDOM               1194
#define IDC_DISTRIBUTION_ORG            1194
#define IDC_ROWNO                       1195
#define IDC_LUXURY                      1195
#define IDC_ROWMISSING                  1196
#define IDC_MAR                         1196
#define IDC_COLSUM                      1197
#define IDC_ENU                         1197
#define IDC_COLMIN                      1198
#define IDC_MISSINGVALUE                1198
#define IDC_COLMAX                      1199
#define IDC_TABLENAME                   1199
#define IDC_COLNO                       1200
#define IDC_CHECK3                      1200
#define IDC_COLMISSING                  1201
#define IDC_STATIC1                     1201
#define IDC_STATIC2                     1202
#define IDC_ABOUT_TEXT                  1203
#define IDC_ABOUT_METHOD                1204
#define IDC_EXPORT                      1205
#define ID_FONT                         1206
#define IDC_EXAMPLE_TEXT                1209
#define IDC_SIZEOFOBJECTS               1210
#define IDC_NUMFRAMES                   1211
#define IDC_SELECTALL                   1212
#define IDC_VISDEC_SPIN                 1215
#define IDC_COLSPIN                     1216
#define IDC_COLDECCHECK                 1217
#define IDC_TABLES                      1219
#define IDC_CLEAR_HISTORY               1220
#define IDC_NUMBER                      1221
#define IDC_ALLOWASSOC                  1222
#define IDC_INFO                        1223
#define IDC_INFO3                       1224
#define IDC_INFO2                       1225
#define IDC_PICTURE                     1226
#define IDC_TEXT                        1227
#define IDC_LIST1                       1229
#define IDC_PATNGENERATEDGROUPS         1230
#define IDC_APRIORIGROUPS               1231
#define IDC_COMBO1                      1233
#define IDC_COMBO2                      1234
#define IDC_COMBO3                      1235
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_TABLE_ROW_INSERT             32775
#define ID_TABLE_ROW_DELETE             32776
#define ID_TABLE_ROW_MAKEEXTRINSIC      32777
#define ID_TABLE_ROW_MAKEINTRINSIC      32778
#define ID_TABLE_ROW_PROPERTIES         32779
#define ID_TABLE_COLUMN_INSERT          32780
#define ID_TABLE_COLUMN_DELETE          32781
#define ID_TABLE_COLUMN_MAKEEXTRINSIC   32782
#define ID_TABLE_COLUMN_MAKEINTRINSIC   32783
#define ID_TABLE_COLUMN_PROPERTIES      32784
#define ID_TABLE_ROW_ADD                32785
#define ID_TABLE_COLUMN_ADD             32786
#define ID_TABLE_PROPERTIES             32787
#define ID_TABLE_FONT                   32802
#define ID_FILE_IMPORT                  32803
#define ID_TABLE_COLUMN_SELECT          32805
#define ID_TABLE_ROW_SELECT             32806
#define ID_TABLE_COLUMN_HIDE            32807
#define ID_TABLE_COLUMN_UNHIDE          32808
#define ID_TABLE_ROW_HIDE               32809
#define ID_TABLE_ROW_UNHIDE             32810
#define ID__HIDE                        32811
#define ID__UNHIDE                      32812
#define ID_TABLE_COLUMN_GOTOEXTRINSICS  32821
#define ID_TABLE_ROW_GOTOEXTRINSICS     32822
#define ID_TOOLS_DATATRANSFORMATION     32826
#define ID_TOOLS_DATAANALYSIS           32827
#define ID_TOOLS_HISTOGRAM              32828
#define ID_VIEW_FUSIONDETAILS           32829
#define ID_VIEW_ASSOCIATIONMATRIX       32830
#define ID_OPTIONS_FONT                 32831
#define ID_TOOLS_WIZARD                 32832
#define ID_VIEW_HISTOGRAM               32835
#define ID_VIEW_TWAYTABLE               32837
#define ID_FILE_LOAD_FUSIONTABLE        32839
#define ID_FILE_EXPORT                  32840
#define ID_TABLE_ROW_GROUPS             32841
#define ID_TABLE_ROW_FIND               32842
#define ID_TABLE_COLUMN_GROUPS          32843
#define ID_TABLE_COLUMN_FIND            32844
#define ID_FILE_LOAD_COLUMNAFFINITYVECTOR 32845
#define ID_FILE_LOAD_ROWAFFINITYVECTOR  32846
#define ID_FILE_EXPORT_COLUMNAFFINITYVECTOR 32847
#define ID_FILE_EXPORT_ROWAFFINITYVECTOR 32848
#define ID_VIEW_GSTA                    32849
#define ID_VIEW_3DGRAPH                 32852
#define ID__ROTATE                      32853
#define ID__MINUSROTATIONSPEED          32854
#define ID__DISPLAYLABELS               32856
#define ID__DISPLAYMST                  32857
#define ID__DISPLAYCENTROIDS            32858
#define ID__SHOWGROUPING                32859
#define ID__SHOWAXIES                   32860
#define ID__ADDTEXTBOX                  32861
#define ID__SHOWSELECTEDONLY            32862
#define ID__PLUSROTATIONSPEED           32863
#define ID_FILE_EXPORT_COLUMNASSOCIATIONMATRIX 32865
#define ID_FILE_EXPORT_ROWASSOCATIONMATRIX 32866
#define ID_FILE_EXPORT_COLUMNFUSIONTABLE 32868
#define ID_FILE_EXPORT_ROWFUSIONTABLE   32869
#define ID_FILE_EXPORT_ORDINATIONCOORDINATES 32870
#define ID_FILE_EXPORT_ROWANISMRESULTS  32871
#define ID_FILE_EXPORT_COLUMNANISMRESULTS 32872
#define ID_VIEW_ROWANISM                32873
#define ID_VIEW_COLUMNANISM             32874
#define ID__GROUPSONLY                  32875
#define ID_FILE_APPEND                  32877
#define ID__SAVEIMAGE                   32880
#define ID__PRINT                       32881
#define ID__PRINTPREVIEW                32882
#define ID__SAVEAS                      32883
#define ID__FONT                        32886
#define ID_VIEW_SCATTERPLOT             32887
#define ID__CHANGEFONT                  32888
#define ID_FONT_CHANGE                  32892
#define ID_FILE_ODBCCONNECTION          32896
#define ID__SAVEIMAGEAS                 32897
#define ID_FILE_EXPORT_PCCRESULTS       32899
#define ID__USEUSERGROUPCOLOURS         32900
#define ID__EXPORT                      32901
#define ID__SAVEASIMAGE                 32902
#define ID__SHOWRANGES                  32905
#define ID__USEBLACKWHITESYMBOLS        32906
#define ID_VIEW_ORDINATIONSTRESS        32907
#define ID_FILE_EXPORT_TABLEANDINFOTABS 32908
#define ID__SELECTGROUPSTATISTICSATTRIBUTE 32909
#define ID__SELECTPCCVECTORS            32910
#define ID_BLACKWHITESYMBOLS            32916
#define ID_FILE_LOAD_ORDINATION         32919
#define ID__FLIPAXES                    32920
#define ID_TABLE_PATTERNSOBJECTS        32921
#define ID_FILE_EXPORT_GROUPSTATISTICS  32922
#define ID__KRUSKALWALLICEOPTIONS       32925
#define ID_FILE_EXPORT_KRUSKALWALLICESTATS 32926
#define ID_VIEW_MCAO                    32927
#define ID_FILE_EXPORT_MCAORAWDATA      32928
#define ID_TOOLS_DATAEVALUATION         32929
#define ID_VIEW_ANOSIMRESULTS           32930
#define ID_VIEW_KRUSKALWALLISRESULTS    32931
#define ID_FILE_EXPORT_MCAORESULTS      32935
#define ID_FILE_EXPORT_HISTORY          32937
#define ID_VIEW_HISTORY                 32938
#define ID_TABLE_TANSPOSEDATALABELS     32939
#define ID__BEST                        32941
#define ID__SAVE                        32942
#define ID_FILE_EXPORT_ANOSIMGROUPPAIRRESULTS 32943
#define ID_FILE_EXPORT_ANOSIMGROUPPAIRAFFINITYVECTORS 32944
#define ID__SAVEGROUPAFFINITYVECTOR     32945
#define ID__USEGROUPBLACKWHITESYMBOLS   32946
#define ID__DISPLAYLEGEND               32948
#define ID_EDIT_OTHERLABELSINCOPYCUT    32952
#define ID_TABLE_SELECTIONOPTIONS       32953
#define ID_FILE_EXPORT_SITECOUNT        32954
#define ID_VIEW_BOXWHISKERSTATISTICS    32955
#define ID__CLOSE                       32957
#define ID_GO                           32958
#define ID_SETFONT                      32961
#define ID_KUP                          32963
#define ID_KDOWN                        32964
#define ID_KLEFT                        32965
#define ID_KRIGHT                       32966
#define ID__RESETROTATION               32967
#define ID_TOGGLEROTATE                 32968
#define ID_VIEW_3DGRAPH_OPENGL          32976
#define ID_VIEW_3DGRAPH_DIRECTX70A      32977
#define ID__SORTALPHABETICALLY          32981
#define ID__OBJECTSIZE                  32982
#define ID__SORTBYTABLEORDER            32986
#define ID__SORTBYKRUSKALWALLIS         32987
#define ID_ADVANCED_SETTNIGS            32988
#define ID_CONTEXTMENU                  32993
#define ID_TOOLS_OPTIONS                32994
#define ID__SAVEVIDEO                   32995
#define ID__VISIBLEDECIMALS_1           33003
#define ID__VISIBLEDECIMALS_2           33004
#define ID__VISIBLEDECIMALS_3           33005
#define ID__VISIBLEDECIMALS_0           33006
#define ID__VISIBLEDECIMALS_4           33007
#define ID__VISIBLEDECIMALS_5           33008
#define ID__VISIBLEDECIMALS_6           33009
#define ID__VISIBLEDECIMALS_7           33010
#define ID__SETROTATION_VIEWXY          33012
#define ID__SETROTATION_VIEWYZ          33013
#define ID__SETROTATION_VIEWXZ          33014
#define ID_SHOWTABLE                    33016
#define ID__BWSYMBOLS                   33017
#define ID_DATA_ROW_CONTROLGROUPS       33018
#define ID__CONTROLINDICATOR            33020
#define ID__LABELS                      33021
#define ID__LABELSSYMBOLS               33024
#define ASSOC_BRAY_CURTIS               33025
#define ID_VIEW_PATNTOOLBAR             33030
#define ID_VIEW_PCCRESULTS              33031
#define ID_HELP_PATNONLINE              33032
#define ID_HELP_DISCUSSIONFORUM         33033
#define ID_VIEW_SCATTERPLOT33034        33034
#define ID_DATA_CONTROLGROUPS           33036
#define ID_IMPORT_APRIORIROWGROUPCOMPOSITION 33037
#define ID_EXPORTANALYSISDATA_APRIORIROWGROUPCOMPOSITION 33038
#define ID__GROUP                       33039
#define ID_GROUP_ANALYSISGROUPSANDCENTROIDS 33040
#define ID_GROUP_APRIORIGROUPSANDCENTROIDS 33042
#define ID_FILE_CHECKFORUPDATE          33043
#define ID_DATA_DELETEDUPLICATEROWS     33045
#define ID_IMPORTANALYSISDATA_ROWLOWER  33046
#define ID_IMPORTANALYSISDATA_COLUMNLOWER 33047
#define ID_IMPORTANALYSISDATA_ROWDENDOGRAMORDER 33048
#define ID_IMPORTANALYSISDATA_COLUMNDENDOGRAMORDER 33049
#define ID_EXPORTEVALUATIONDATA_COLUMNGROUPSTATISTICS 33050
#define ID_DATA_CREATENEWVARIABLESREPRESENTINGGROUPS 33051
#define ID__SYMBOLSIZE                  33053
#define ID_SYMBOLSIZE_INCREASEPGUP      33054
#define ID_SYMBOLSIZE_DECREASEPGDN      33055
#define ID__STAT                        33058
#define ID__INCREASESIZE                33059
#define ID__DECREASESYMBOLSIZE          33060
#define ID_TEST                         33061
#define ID__ZOOM                        33062
#define ID_DATA_SWAPROWINTRINSICSWITHEXTRINSICS 33077
#define ID_DATA_SWAPCOLUMNINTRINSICSWITHEXTRINSICS 33078
#define ID_DATA_VARIABLES_KW_TO_EXTRINSICS 33080
#define ID_DATA_CONSTANCYANDFIDELITY    33081
#define ID_SELECTIONS_SAVE              33082
#define ID_SELECTIONS_EDITSELECTIONS    33083
#define ID_SELECTIONS_CLEAR             33084
#define ID_SELECTIONS_SELECTION1        33085
#define ID_SELECTION1_ACTIVATE          33087
#define ID_SELECTIONS_SELECITON2        33088
#define ID_SELECTIONS_SELECTION3        33091
#define ID_SELECTION3_ACTIVATE          33092
#define ID_SELECTION3_SAVECURRENTSELECTION 33093
#define ID_SELECTIONS_ISELECITON4       33094
#define ID_SELECTIONS_SELECTION5        33097
#define ID_SELECTION5_ACTIVATE          33098
#define ID_SELECTION5_SAVECURRENTSELECTION 33099
#define ID_SELECTIONS_SELECTION         33100
#define ID_SELECTION6_ACTIVATE          33105
#define ID_SELECTION6_SAVECURRENTSELECTION 33106
#define ID_SELECTION1_SAVECURRENTSELECTION 33107
#define ID_SELECTION2_ACTIVATE          33108
#define ID_SELECTION2_SAVECURRENTSELECTION 33109
#define ID_SELECTION4_SAVECURRENTSELECTION 33110
#define ID_SELECTION4_ACTIVATE          33111
#define ID_DATA_ASSIGNGROUPSTONON       33112
#define ID__PICKACOLUMN                 33113
#define ID_VIEW_CONSTFID                33116
#define ASSOC_GOWER_METRIC              61447
#define ASSOC_MINKOWSKI_SERIES          61448
#define ASSOC_TWO_STEP                  61449
#define ASSOC_KULZINSKI                 61450
#define CLASS_FUSE                      61451
#define CLASS_ALLOC                     61452
#define FUSE_NEAREST_NEIGHBOUR          61453
#define FUSE_FURTHEST_NEIGHBOUR         61454
#define FUSE_FLEXIBLE_WPGMA             61455
#define FUSE_FLEXIBLE_UPGMA             61456

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        288
#define _APS_NEXT_COMMAND_VALUE         33118
#define _APS_NEXT_CONTROL_VALUE         1236
#define _APS_NEXT_SYMED_VALUE           236
#endif
#endif
